name: Get Citation Data

on: 
 page_build: 
 schedule:
  - cron:  '0 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: true
    - name: Install Reqs
      run: |
        sudo apt-get install python3-setuptools
    - name: Run
      run: |
        cd ./google_crawler
        pip3 install -r requirements.txt
        python3 main.py
        git add "../assets/google_scholar/"
        git config --global user.email "itisandrewlee@gmail.com"
        git config --global user.name "andrewcwlee"
        git commit -m "* update `date '+%Y-%m-%d %H:%M:%S'`"
        git push